global:
  scrape_interval: 15s
  evaluation_interval: 15s



scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_api"
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:8089"]
  - job_name: "java_api"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ["127.0.0.1:8080"]

